draw:
  # Defines the direction of graph layout. See: https://graphviz.org/docs/attrs/rankdir/
  # orientation: LR
  # Filters for matching and excluding resources by name.
  filters:
    sqs:
      # Patterns to exclude
      not_match:
        - "dlq$"