// Code generated by MockGen. DO NOT EDIT.
// Source: survey.go
//
// Generated by this command:
//
//	mockgen -package survey -destination survey_mock.go -source survey.go
//

// Package survey is a generated GoMock package.
package survey

import (
	reflect "reflect"

	v2 "github.com/AlecAivazis/survey/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockSurveyAsker is a mock of SurveyAsker interface.
type MockSurveyAsker struct {
	ctrl     *gomock.Controller
	recorder *MockSurveyAskerMockRecorder
}

// MockSurveyAskerMockRecorder is the mock recorder for MockSurveyAsker.
type MockSurveyAskerMockRecorder struct {
	mock *MockSurveyAsker
}

// NewMockSurveyAsker creates a new mock instance.
func NewMockSurveyAsker(ctrl *gomock.Controller) *MockSurveyAsker {
	mock := &MockSurveyAsker{ctrl: ctrl}
	mock.recorder = &MockSurveyAskerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSurveyAsker) EXPECT() *MockSurveyAskerMockRecorder {
	return m.recorder
}

// Ask mocks base method.
func (m *MockSurveyAsker) Ask(questions []*v2.Question, answers any, opts ...v2.AskOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{questions, answers}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Ask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ask indicates an expected call of Ask.
func (mr *MockSurveyAskerMockRecorder) Ask(questions, answers any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{questions, answers}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ask", reflect.TypeOf((*MockSurveyAsker)(nil).Ask), varargs...)
}

// AskOne mocks base method.
func (m *MockSurveyAsker) AskOne(p v2.Prompt, response any, opts ...v2.AskOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{p, response}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AskOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AskOne indicates an expected call of AskOne.
func (mr *MockSurveyAskerMockRecorder) AskOne(p, response any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{p, response}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskOne", reflect.TypeOf((*MockSurveyAsker)(nil).AskOne), varargs...)
}
