version: "3"

vars:
  LINT_TIMEOUT: 5m
  GOTEST_ARGS: -count=1 -v -failfast

tasks:
  install:
    desc: "Install all project tools"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install go.uber.org/mock/mockgen@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install mvdan.cc/gofumpt@v0.4.0

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint version
      - golangci-lint run -v --timeout="{{.LINT_TIMEOUT}}" {{.USER_WORKING_DIR}}/...

  fmt:
    desc: "Format code"
    cmds:
      - goimports -w . && gofumpt -l -w .

  tests:
    desc: "Run all tests"
    cmds:
      - go test {{.GOTEST_ARGS}} -cover {{.USER_WORKING_DIR}}/...

  cov:
    desc: "Run code coverage"
    cmds:
      - go test {{.GOTEST_ARGS}} -covermode=count -coverpkg=../... -coverprofile=coverage.out -cover ../...
      - cat coverage.out | grep -v "mock" > coverage.nomocks.out
      - go tool cover -func coverage.nomocks.out > coverage.out
  
  cov-badge:
    desc: "Update coverage badge in the README"
    cmds:
      # - task: coverage
      - ./update_coverage.sh ./coverage.out {{.USER_WORKING_DIR}}/README.md